FROM ubuntu:22.04

# Install Java 17
RUN apt-get update && apt-get install -y openjdk-17-jdk wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY target/employee-dynamic-app-1.0.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
